### ISSUE TITLE
NAO TA FUNCIONANDO

### ISSUE THREAD

**Issue by ricardobg** [arthurkenzosato/VSCryptoPoker#1]

**Comment by arthurkms** [comment]
É necessário instalar o Python primeiro

**Comment by ricardobg** [comment]
QUE ISSO?

**Comment by adrianodennanni** [comment]
Roda no Laptop da Xuxa?????????

**Comment by ThiagoLira** [comment]
EU PEDI UM PYTHON PELO MERCADO LIVRE E FUI PICADO POR UMA COBRA 0/10

**Comment by arthurkms** [comment]
É necessário importar o plugin para domesticar o bixo, qualquer coisa pede para a assistencia técnica (81) 34648400
