### ISSUE TITLE
COMO ESTALA PAITON NO WINDOWS XP????

### ISSUE THREAD

**Issue by adrianodennanni** [arthurkenzosato/VSCryptoPoker#3]
NAO SEI ESTALAR PAITON NO WINDOWS XP COM 2 GIBAS DE MEMÓRIA RAMBO E NAVEGADOR GODZILA GIROFLEX

**Comment by arthurkms** [comment]
Tem que encomendar no Mercado Livre, pede a versão 2.7.11 64 bits, vai sair um pouco mais caro, mas eu garanto que vale muito a pena.

**Comment by adrianodennanni** [comment]
#PAS
